version: "3.8"
services:
  tensorflow:
    image: tensorflow
    container_name: jupyterLAB
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    volumes:
      - type: bind
        source: $PWD
        target: /hamidadesokan/notebooks/
          #- "/Users/hamidadesokan/Dropbox/7_Technical_Writing/D-Aimix/Aimix:/hamidadesokan/notebooks"
